### ISSUE TITLE
Error importing to mysql 

### ISSUE THREAD

**Issue by cantfish** [ESX-PUBLIC/esx_fishing#2]
_**THIS HAPPENS WHEN I TRY TO IMPORT THE SQL**_
Preparing...
Importing esx_fishingjob_en.sql...
Finished executing script
ERROR 1062 (23000) at line 3: Duplicate entry 'fish' for key 'PRIMARY'
Operation failed with exitcode 1

**Comment by rex2630** [comment]
Because u already have that item in the DB, thats why.
